
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApplicationBar from "./ApplicationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <div className="grid grid-rows-[20px_1fr_20px]  min-h-screen font-[family-name:var(--font-geist-sans)]">
<ApplicationBar />
<div></div>
        </div>
        {children}
      </body>
    </html>
  );
}
